apiVersion: 1

datasources:
  - name: PostgreSQL
    type: postgres
    uid: postgres
    access: proxy
    url: postgres:5432
    user: postgres
    secureJsonData:
      password: postgres
    jsonData:
      database: dexdb
      sslmode: disable
      maxOpenConns: 5
      maxIdleConns: 5
      connMaxLifetime: 14400
      postgresVersion: 1500
      timescaledb: false
    isDefault: false
    editable: false
